# Part of the Invenio-Stats-Dashboard extension for InvenioRDM
# Copyright (C) 2025 Mesh Research
#
# Invenio-Stats-Dashboard is free software; you can redistribute it and/or modify
# it under the terms of the MIT License; see LICENSE file for more details.

"""Sample usage snapshot data series response."""

MOCK_USAGE_SNAPSHOT_DATA_SERIES = {
    "access_statuses": {
        "data_volume": [
            {
                "data": [["06-01", 5120.0]],
                "year": 2025,
                "id": "metadata-only",
                "name": "Metadata Only",
                "type": "line",
                "valueType": "number",
            },
            {
                "data": [["06-01", 15360.0]],
                "year": 2025,
                "id": "with-files",
                "name": "With Files",
                "type": "line",
                "valueType": "number",
            },
        ],
        "download_unique_files": [
            {
                "data": [["06-01", 4]],
                "year": 2025,
                "id": "metadata-only",
                "name": "Metadata Only",
                "type": "line",
                "valueType": "number",
            },
            {
                "data": [["06-01", 10]],
                "year": 2025,
                "id": "with-files",
                "name": "With Files",
                "type": "line",
                "valueType": "number",
            },
        ],
        "download_unique_parents": [
            {
                "data": [["06-01", 3]],
                "year": 2025,
                "id": "metadata-only",
                "name": "Metadata Only",
                "type": "line",
                "valueType": "number",
            },
            {
                "data": [["06-01", 7]],
                "year": 2025,
                "id": "with-files",
                "name": "With Files",
                "type": "line",
                "valueType": "number",
            },
        ],
        "download_unique_records": [
            {
                "data": [["06-01", 5]],
                "year": 2025,
                "id": "metadata-only",
                "name": "Metadata Only",
                "type": "line",
                "valueType": "number",
            },
            {
                "data": [["06-01", 9]],
                "year": 2025,
                "id": "with-files",
                "name": "With Files",
                "type": "line",
                "valueType": "number",
            },
        ],
        "download_visitors": [
            {
                "data": [["06-01", 2]],
                "year": 2025,
                "id": "metadata-only",
                "name": "Metadata Only",
                "type": "line",
                "valueType": "number",
            },
            {
                "data": [["06-01", 4]],
                "year": 2025,
                "id": "with-files",
                "name": "With Files",
                "type": "line",
                "valueType": "number",
            },
        ],
        "downloads": [
            {
                "data": [["06-01", 5]],
                "year": 2025,
                "id": "metadata-only",
                "name": "Metadata Only",
                "type": "line",
                "valueType": "number",
            },
            {
                "data": [["06-01", 12]],
                "year": 2025,
                "id": "with-files",
                "name": "With Files",
                "type": "line",
                "valueType": "number",
            },
        ],
        "view_unique_parents": [
            {
                "data": [["06-01", 5]],
                "year": 2025,
                "id": "metadata-only",
                "name": "Metadata Only",
                "type": "line",
                "valueType": "number",
            },
            {
                "data": [["06-01", 8]],
                "year": 2025,
                "id": "with-files",
                "name": "With Files",
                "type": "line",
                "valueType": "number",
            },
        ],
        "view_unique_records": [
            {
                "data": [["06-01", 8]],
                "year": 2025,
                "id": "metadata-only",
                "name": "Metadata Only",
                "type": "line",
                "valueType": "number",
            },
            {
                "data": [["06-01", 12]],
                "year": 2025,
                "id": "with-files",
                "name": "With Files",
                "type": "line",
                "valueType": "number",
            },
        ],
        "view_visitors": [
            {
                "data": [["06-01", 3]],
                "year": 2025,
                "id": "metadata-only",
                "name": "Metadata Only",
                "type": "line",
                "valueType": "number",
            },
            {
                "data": [["06-01", 6]],
                "year": 2025,
                "id": "with-files",
                "name": "With Files",
                "type": "line",
                "valueType": "number",
            },
        ],
        "views": [
            {
                "data": [["06-01", 10]],
                "year": 2025,
                "id": "metadata-only",
                "name": "Metadata Only",
                "type": "line",
                "valueType": "number",
            },
            {
                "data": [["06-01", 15]],
                "year": 2025,
                "id": "with-files",
                "name": "With Files",
                "type": "line",
                "valueType": "number",
            },
        ],
    },
    "affiliations_by_download": {
        "data_volume": [],
        "download_visitors": [],
        "downloads": [],
        "view_visitors": [],
        "views": [],
    },
    "affiliations_by_view": {
        "data_volume": [],
        "download_visitors": [],
        "downloads": [],
        "view_visitors": [],
        "views": [],
    },
    "countries_by_download": {
        "data_volume": [
            {
                "data": [["06-01", 10240.0]],
                "year": 2025,
                "id": "US",
                "name": "United States",
                "type": "line",
                "valueType": "number",
            },
            {
                "data": [["06-01", 2048.0]],
                "year": 2025,
                "id": "CA",
                "name": "Canada",
                "type": "line",
                "valueType": "number",
            },
        ],
        "download_visitors": [
            {
                "data": [["06-01", 4]],
                "year": 2025,
                "id": "US",
                "name": "United States",
                "type": "line",
                "valueType": "number",
            },
            {
                "data": [["06-01", 1]],
                "year": 2025,
                "id": "CA",
                "name": "Canada",
                "type": "line",
                "valueType": "number",
            },
        ],
        "downloads": [
            {
                "data": [["06-01", 10]],
                "year": 2025,
                "id": "US",
                "name": "United States",
                "type": "line",
                "valueType": "number",
            },
            {
                "data": [["06-01", 4]],
                "year": 2025,
                "id": "CA",
                "name": "Canada",
                "type": "line",
                "valueType": "number",
            },
        ],
        "view_visitors": [
            {
                "data": [["06-01", 7]],
                "year": 2025,
                "id": "US",
                "name": "United States",
                "type": "line",
                "valueType": "number",
            },
            {
                "data": [["06-01", 3]],
                "year": 2025,
                "id": "CA",
                "name": "Canada",
                "type": "line",
                "valueType": "number",
            },
        ],
        "views": [
            {
                "data": [["06-01", 18]],
                "year": 2025,
                "id": "US",
                "name": "United States",
                "type": "line",
                "valueType": "number",
            },
            {
                "data": [["06-01", 8]],
                "year": 2025,
                "id": "CA",
                "name": "Canada",
                "type": "line",
                "valueType": "number",
            },
        ],
    },
    "countries_by_view": {
        "data_volume": [
            {
                "data": [["06-01", 8192.0]],
                "year": 2025,
                "id": "US",
                "name": "United States",
                "type": "line",
                "valueType": "number",
            },
            {
                "data": [["06-01", 4096.0]],
                "year": 2025,
                "id": "CA",
                "name": "Canada",
                "type": "line",
                "valueType": "number",
            },
        ],
        "download_visitors": [
            {
                "data": [["06-01", 3]],
                "year": 2025,
                "id": "US",
                "name": "United States",
                "type": "line",
                "valueType": "number",
            },
            {
                "data": [["06-01", 2]],
                "year": 2025,
                "id": "CA",
                "name": "Canada",
                "type": "line",
                "valueType": "number",
            },
        ],
        "downloads": [
            {
                "data": [["06-01", 8]],
                "year": 2025,
                "id": "US",
                "name": "United States",
                "type": "line",
                "valueType": "number",
            },
            {
                "data": [["06-01", 6]],
                "year": 2025,
                "id": "CA",
                "name": "Canada",
                "type": "line",
                "valueType": "number",
            },
        ],
        "view_visitors": [
            {
                "data": [["06-01", 8]],
                "year": 2025,
                "id": "US",
                "name": "United States",
                "type": "line",
                "valueType": "number",
            },
            {
                "data": [["06-01", 4]],
                "year": 2025,
                "id": "CA",
                "name": "Canada",
                "type": "line",
                "valueType": "number",
            },
        ],
        "views": [
            {
                "data": [["06-01", 20]],
                "year": 2025,
                "id": "US",
                "name": "United States",
                "type": "line",
                "valueType": "number",
            },
            {
                "data": [["06-01", 12]],
                "year": 2025,
                "id": "CA",
                "name": "Canada",
                "type": "line",
                "valueType": "number",
            },
        ],
    },
    "file_types": {
        "data_volume": [],
        "download_unique_files": [],
        "download_unique_parents": [],
        "download_unique_records": [],
        "download_visitors": [],
        "downloads": [],
        "view_unique_parents": [],
        "view_unique_records": [],
        "view_visitors": [],
        "views": [],
    },
    "funders_by_download": {
        "data_volume": [],
        "download_unique_files": [],
        "download_unique_parents": [],
        "download_unique_records": [],
        "download_visitors": [],
        "downloads": [],
        "view_unique_parents": [],
        "view_unique_records": [],
        "view_visitors": [],
        "views": [],
    },
    "funders_by_view": {
        "data_volume": [],
        "download_unique_files": [],
        "download_unique_parents": [],
        "download_unique_records": [],
        "download_visitors": [],
        "downloads": [],
        "view_unique_parents": [],
        "view_unique_records": [],
        "view_visitors": [],
        "views": [],
    },
    "global": {
        "data_volume": [
            {
                "data": [["06-01", 20480.0]],
                "year": 2025,
                "id": "global",
                "name": "Global",
                "type": "bar",
                "valueType": "number",
            }
        ],
        "download_unique_files": [
            {
                "data": [["06-01", 20]],
                "year": 2025,
                "id": "global",
                "name": "Global",
                "type": "bar",
                "valueType": "number",
            }
        ],
        "download_unique_parents": [
            {
                "data": [["06-01", 15]],
                "year": 2025,
                "id": "global",
                "name": "Global",
                "type": "bar",
                "valueType": "number",
            }
        ],
        "download_unique_records": [
            {
                "data": [["06-01", 20]],
                "year": 2025,
                "id": "global",
                "name": "Global",
                "type": "bar",
                "valueType": "number",
            }
        ],
        "download_visitors": [
            {
                "data": [["06-01", 10]],
                "year": 2025,
                "id": "global",
                "name": "Global",
                "type": "bar",
                "valueType": "number",
            }
        ],
        "downloads": [
            {
                "data": [["06-01", 25]],
                "year": 2025,
                "id": "global",
                "name": "Global",
                "type": "bar",
                "valueType": "number",
            }
        ],
        "view_unique_parents": [
            {
                "data": [["06-01", 25]],
                "year": 2025,
                "id": "global",
                "name": "Global",
                "type": "bar",
                "valueType": "number",
            }
        ],
        "view_unique_records": [
            {
                "data": [["06-01", 35]],
                "year": 2025,
                "id": "global",
                "name": "Global",
                "type": "bar",
                "valueType": "number",
            }
        ],
        "view_visitors": [
            {
                "data": [["06-01", 18]],
                "year": 2025,
                "id": "global",
                "name": "Global",
                "type": "bar",
                "valueType": "number",
            }
        ],
        "views": [
            {
                "data": [["06-01", 45]],
                "year": 2025,
                "id": "global",
                "name": "Global",
                "type": "bar",
                "valueType": "number",
            }
        ],
    },
    "languages_by_download": {
        "data_volume": [],
        "download_unique_files": [],
        "download_unique_parents": [],
        "download_unique_records": [],
        "download_visitors": [],
        "downloads": [],
        "view_unique_parents": [],
        "view_unique_records": [],
        "view_visitors": [],
        "views": [],
    },
    "languages_by_view": {
        "data_volume": [],
        "download_unique_files": [],
        "download_unique_parents": [],
        "download_unique_records": [],
        "download_visitors": [],
        "downloads": [],
        "view_unique_parents": [],
        "view_unique_records": [],
        "view_visitors": [],
        "views": [],
    },
    "periodicals_by_download": {
        "data_volume": [],
        "download_unique_files": [],
        "download_unique_parents": [],
        "download_unique_records": [],
        "download_visitors": [],
        "downloads": [],
        "view_unique_parents": [],
        "view_unique_records": [],
        "view_visitors": [],
        "views": [],
    },
    "periodicals_by_view": {
        "data_volume": [],
        "download_unique_files": [],
        "download_unique_parents": [],
        "download_unique_records": [],
        "download_visitors": [],
        "downloads": [],
        "view_unique_parents": [],
        "view_unique_records": [],
        "view_visitors": [],
        "views": [],
    },
    "publishers_by_download": {
        "data_volume": [],
        "download_visitors": [],
        "downloads": [],
        "view_visitors": [],
        "views": [],
    },
    "publishers_by_view": {
        "data_volume": [],
        "download_visitors": [],
        "downloads": [],
        "view_visitors": [],
        "views": [],
    },
    # "referrers_by_download": {  # disabled for usage events
        # "data_volume": [],
        # "download_visitors": [],
        # "downloads": [],
        # "view_visitors": [],
        # "views": [],
    # },
    # "referrers_by_view": {  # disabled for usage events
        # "data_volume": [],
        # "download_visitors": [],
        # "downloads": [],
        # "view_visitors": [],
        # "views": [],
    # },
    "resource_types": {
        "data_volume": [],
        "download_unique_files": [],
        "download_unique_parents": [],
        "download_unique_records": [],
        "download_visitors": [],
        "downloads": [],
        "view_unique_parents": [],
        "view_unique_records": [],
        "view_visitors": [],
        "views": [],
    },
    "rights_by_download": {
        "data_volume": [],
        "download_visitors": [],
        "downloads": [],
        "view_visitors": [],
        "views": [],
    },
    "rights_by_view": {
        "data_volume": [],
        "download_visitors": [],
        "downloads": [],
        "view_visitors": [],
        "views": [],
    },
    # "subjects_by_download": {  # disabled for usage events
        # "data_volume": [],
        # "download_visitors": [],
        # "downloads": [],
        # "view_visitors": [],
        # "views": [],
    # },
    # "subjects_by_view": {  # disabled for usage events
        # "data_volume": [],
        # "download_visitors": [],
        # "downloads": [],
        # "view_visitors": [],
        # "views": [],
    # },
}
